### ISSUE TITLE
deploying to prisma cluster generates unsuable endpoints

### ISSUE THREAD

**Issue by sixtatami** [graphcool/prisma#1945]
When following the installation guidelines for the Node advanced template and deploying to prisma-eu1, following endpoints were created:

Service Name: wisy-6
  dev (cluster: `prisma-eu1`)
    HTTP:       https://eu1.prisma.sh/wisy-6/dev
    Websocket:  https://eu1.prisma.sh/wisy-6/dev

However it is not possible to connect to those, or I don't know how.

**Comment by sixtatami** [comment]
I realized that my account has no name, even though I don't know why I don't have a name as I logged in via Github. However, maybe this adds to the problem creating the URL for the endpoint. Don't know though

**Comment by robmurtagh** [comment]
I have an identical issue. Tried `prism init` with both `prisma@1.2.4` and `prisma@1.2.4`. In both cases the follwing is generated in `.env`:
```
PRISMA_ENDPOINT="https://eu1.prisma.sh/experiments-prisma/dev"
```
When you open the playground there is no schema and refreshing gives the error `Server cannot be reached`

**Comment by n2ctech** [comment]
same

**Comment by timsuchanek** [comment]
Thanks for reporting everybody! Please try the latest beta - there it should be fixed!

**Comment by robmurtagh** [comment]
Thanks @timsuchanek , how do we install the beta CLI?

**Comment by timsuchanek** [comment]
@robmurtagh  Just updated the comment :)

**Comment by robmurtagh** [comment]
@timsuchanek Still getting the same error:

```
> prisma init

? How to set up a new Prisma service? 

Running $ graphql create ...                             
? Directory for new GraphQL project ./experiments-prisma-beta
? Choose GraphQL boilerplate project: node-advanced           GraphQL server (incl. database & authentication)
[graphql create] Downloading boilerplate from https://github.com/graphql-boilerplates/node-graphql-server/archive/master.zip...
[graphql create] Installing node dependencies for /Users/robmurtagh/Drive/Code_Picnic/picnic_web/experiments-prisma-beta/package.json...
yarn install v1.3.2
warning package.json: No license field
warning graphql-boilerplate: No license field
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "graphql-yoga > apollo-upload-server@4.0.0-alpha.3" has incorrect peer dependency "graphql@0.11 - 0.12".
warning "graphql-yoga > graphql-subscriptions@0.5.6" has incorrect peer dependency "graphql@^0.10.5 || ^0.11.3 || ^0.12.0".
warning "graphql-yoga > graphql-tools@2.18.0" has incorrect peer dependency "graphql@^0.11.0 || ^0.12.0".
warning "graphql-yoga > subscriptions-transport-ws@0.9.5" has incorrect peer dependency "graphql@^0.10.0 || ^0.11.0 || ^0.12.0".
warning "graphql-yoga > apollo-server-express > apollo-server-core@1.3.2" has incorrect peer dependency "graphql@^0.9.0 || ^0.10.0 || ^0.11.0 || ^0.12.0".
warning "prisma-binding > apollo-link@1.0.7" has unmet peer dependency "graphql@^0.11.3 || ^0.12.3".
warning "graphql-yoga > apollo-server-express > apollo-server-core > apollo-cache-control@0.0.9" has incorrect peer dependency "graphql@^0.10.0 || ^0.11.0 || ^0.12.0".
warning "graphql-yoga > apollo-server-express > apollo-server-core > apollo-tracing@0.1.3" has incorrect peer dependency "graphql@^0.10.0 || ^0.11.0 || ^0.12.0".
warning "graphql-yoga > apollo-server-express > apollo-server-core > graphql-extensions@0.0.7" has incorrect peer dependency "graphql@^0.10.0 || ^0.11.0 || ^0.12.0".
warning " > prisma-binding@1.5.12" has unmet peer dependency "graphql@0.13.0".
warning "prisma-binding > graphql-binding@1.2.2" has unmet peer dependency "graphql@^0.11.0 || ^0.12.0 || ^0.13.0".
warning "prisma-binding > graphql-tools@2.20.2" has unmet peer dependency "graphql@^0.11.0 || ^0.12.0".
warning "prisma-binding > graphql-binding > graphql-tools@2.21.0" has unmet peer dependency "graphql@^0.11.0 || ^0.12.0 || ^0.13.0".
warning "prisma-binding > graphql-binding > graphql-tools > apollo-link@1.1.0" has unmet peer dependency "graphql@^0.11.3 || ^0.12.3 || ^0.13.0".
warning "prisma > prisma-cli-core > graphql-cli > graphql-playground-middleware-express@1.5.2" has unmet peer dependency "express@^4.16.2".
[4/4] 📃  Building fresh packages...
✨  Done in 18.02s.
[graphql create] Installing node dependencies for /Users/.../Drive/Code_Picnic/picnic_web/experiments-prisma-beta/.install/package.json...
yarn install v1.3.2
warning package.json: No license field
warning ../package.json: No license field
warning install@0.0.0: No license field
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > graphql-boilerplate-install@0.1.8" has unmet peer dependency "prisma@1.0.4".
[4/4] 📃  Building fresh packages...
✨  Done in 0.39s.
[graphql create] Running boilerplate install script... 
Running $ prisma deploy...

? Please choose the cluster you want to deploy "experiments-prisma-beta@dev" to 
Added cluster: prisma-eu1 to prisma.yml
Creating stage dev for service experiments-prisma-beta ✔
Deploying service `experiments-prisma-beta` to stage `dev` on cluster `[account-name]/prisma-eu1` 110ms

Changes:

  Post (Type)
  + Created type `Post`
  + Created field `id` of type `GraphQLID!`
  + Created field `createdAt` of type `DateTime!`
  + Created field `updatedAt` of type `DateTime!`
  + Created field `isPublished` of type `Boolean!`
  + Created field `title` of type `String!`
  + Created field `text` of type `String!`
  + Created field `author` of type `Relation!`

  User (Type)
  + Created type `User`
  + Created field `id` of type `GraphQLID!`
  + Created field `email` of type `String!`
  + Created field `password` of type `String!`
  + Created field `name` of type `String!`
  + Created field `posts` of type `[Relation!]!`
  + Created field `updatedAt` of type `DateTime!`
  + Created field `createdAt` of type `DateTime!`

  PostToUser (Relation)
  + Created relation between Post and User

Applying changes 1.2s

Hooks:
Importing seed dataset from `seed.graphql` 170ms

Your GraphQL database endpoint is live:

  HTTP:  https://eu1.prisma.sh/experiments-prisma-beta/dev
  WS:    https://eu1.prisma.sh/experiments-prisma-beta/dev

Checking, if schema file changed 1.2s
Writing database schema to `src/generated/prisma.graphql`  1ms
Running $ graphql prepare...

Next steps:
  1. Change directory: `cd ./experiments-prisma-beta`
  2. Start local server and open Playground: `yarn dev`
```

When I go to `https://eu1.prisma.sh/experiments-prisma-beta/dev` and refresh, it says `Server cannot be reached`, and there is no GraphQL server in the playground...

Am I doing something stupid?

**Comment by marktani** [comment]
Hey @robmurtagh, so sorry for your experience. You're not doing anything stupid 😄 

The boilerplates use a dev dependency to `prisma`. This means they use the latest stable version, no matter what your global version is.

I just created a new `beta` branch in the node boilerplate repository, so you should be able to run the following:

```
graphql create --boilerplate https://github.com/graphql-boilerplates/node-graphql-server/tree/beta/advanced
```

to create a new service with the latest `beta` version 🙂

**Comment by timsuchanek** [comment]
It's now fixed - the endpoints are correct again.
Just update the `prisma` cli to 1.2.5:
`npm install -g prisma`
